# Generated by Django 6.0.6 on 2026-06-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_post_createdby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdby',
            new_name='created_by',
        ),
    ]
